---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8tcher
  namespace: kube-system
---

apiVersion: v1
kind: Pod
metadata:
  name: k8tcher
  namespace: kube-system 
spec:
  hostNetwork: true
  serviceAccountName: k8tcher
  containers:
  - image: abhinandan03/k8tcher:latest
    imagePullPolicy: Always
    name: k8tcher
